version: '3.5'

services:
  io_kiyar_sharup_server:
    image: io_kiyar_sharup_server
    container_name: io_kiyar_sharup_server
    restart: always
    build: .
    ports:
      - '3090:2805'
    environment:
      - PORT=80
    networks:
      - nginx

networks:
  nginx:
    external:
      name: nginx